custom_plugins_dir: /var/lib/jmfzf/plugins
plugins:
- ec2:
  private: true
- cvm:
  access_key: xxxxxxxxxxxxxxxxx
  access_key_secret: xxxxxxxxxxxxxxxxx
  template: "{{.Name}}-{{.PublicIP}}-{{.PrivateIP}}"
  zone: 
  - ap-guangzhou
  - ap-shanghai
  tags:
  - name: tag1
    value: value1
  - name: tag2
    value: value2
- ecs: {}
- bce: {}
- jumpserver:
  url: http://your-jumpserver.com/api
  access_key: xxxxxxxxxxxxxxxxxxxxxxxxx
  access_key_secret: xxxxxxxxxxxxxxxxxxxxxxxxx
  api_token: token-xxxxxxxxxxxxxxxxxxxxxxxx
- sshconfig:
  - ~/.ssh/config
- docker:
  host: unix:///var/run/docker.sock
- kubernetes:
  kubeconfig: ~/.kube/config
  namespaces:
  - default
  - kube-system
  - kube-public
  - kube-node-lease